"! STUB — abap-mcp's own declaration of this type's public signature, NOT SAP source.
"! Exists only so abaplint can type-check code generated by scaffold_abap_ai_sdk (see
"! src/data/abap-ai-sdk.json, curatedDate 2026-09-10). The real interface ships inside
"! SAP's ABAP AI SDK powered by ISLM — never import this file into an actual SAP system.
"! Method shapes verified against SAP Help "Calling The Completion API" / "Function
"! Calling" / "Format Specification Of Completion API Response".
INTERFACE if_aic_completion_api PUBLIC.

  METHODS execute_for_string
    IMPORTING prompt        TYPE string
    RETURNING VALUE(result) TYPE REF TO if_aic_completion_api_result
    RAISING   cx_aic_completion_api.

  METHODS execute_for_messages
    IMPORTING messages      TYPE REF TO if_aic_message_container
    RETURNING VALUE(result) TYPE REF TO if_aic_completion_api_result
    RAISING   cx_aic_completion_api.

  METHODS create_message_container
    RETURNING VALUE(result) TYPE REF TO if_aic_message_container.

  METHODS get_parameter_setter
    RETURNING VALUE(result) TYPE REF TO if_aic_completion_parameters.

  METHODS register_function
    IMPORTING name          TYPE string
    RETURNING VALUE(result) TYPE REF TO if_aic_function_definition.

  METHODS define_response_format
    RETURNING VALUE(result) TYPE REF TO if_aic_response_format_definition.

ENDINTERFACE.
