/**
 * ABAP Unit test-class scaffolding — the "day 2" consultant task.
 *
 * Given class sources, generate the local test-class include
 * (`<class>.clas.testclasses.abap`) with one skeleton test method per public
 * method: setup instantiates the CUT, every test method fails loudly with a
 * TODO so a generated-but-empty test can never masquerade as coverage.
 *
 * Same honesty tiering as the RAP scaffolder: generated code is round-tripped
 * through abaplint (together with the class under test) before it is returned.
 * Skeletons are syntax-validated structure — the given/when/then substance is
 * the developer's (or the agent's) job, and the fail( ) markers enforce that.
 */
import type { AbapSource, AbapVersion, Finding } from "./engine.js";
import { inferFilename, runAbaplint } from "./engine.js";
import { invalidInput } from "../errors.js";
import type { ClassOutline } from "./outline.js";
import { outlineAbap } from "./outline.js";

export interface UnitTestFile {
  /** abapGit-style filename, e.g. "zcl_travel.clas.testclasses.abap". */
  filename: string;
  content: string;
  /** Global class the tests target. */
  forClass: string;
  /** Same tiering as scaffold_rap_bo: "abaplint" = parser round-tripped. */
  validated: "abaplint";
}

export interface UnitTestResult {
  files: UnitTestFile[];
  /** Classes that were skipped and why (interfaces-only files, FOR TESTING classes, …). */
  skipped: { object: string; reason: string }[];
  nextSteps: string[];
  /** abaplint findings on the generated code — empty on a clean round-trip. */
  validationIssues: Finding[];
}

/** Method names that never get a test skeleton. */
const NON_TESTABLE = new Set(["constructor", "class_constructor"]);

const MAX_METHOD_NAME = 30;

function testClassName(cut: string): string {
  const stem = cut.toLowerCase().replace(/^z?cl_|^ycl_|^cl_/, "");
  return `ltc_${stem}`.slice(0, MAX_METHOD_NAME);
}

function renderTestClass(cut: ClassOutline): string {
  const ltc = testClassName(cut.name);
  const cutName = cut.name.toLowerCase();
  const methods = cut.methods
    .filter((m) => m.visibility === "public" && !NON_TESTABLE.has(m.name.toLowerCase()))
    .map((m) => m.name.toLowerCase().slice(0, MAX_METHOD_NAME));
  const testMethods = methods.length > 0 ? [...new Set(methods)] : ["instantiation"];
  const hasCtorParams = cut.methods.some((m) => m.name.toLowerCase() === "constructor");

  const defn = [
    `"! Generated by abap-mcp scaffold_abap_unit — skeletons only.`,
    `"! Replace every fail( ) marker with real given/when/then logic.`,
    `CLASS ${ltc} DEFINITION FINAL FOR TESTING`,
    `  RISK LEVEL HARMLESS DURATION SHORT.`,
    `  PRIVATE SECTION.`,
    `    DATA cut TYPE REF TO ${cutName}.`,
    `    METHODS setup.`,
    ...testMethods.map((m) => `    METHODS ${m} FOR TESTING.`),
    `ENDCLASS.`,
  ].join("\n");

  const setupBody = cut.isAbstract
    ? [
        `    " ${cutName} is abstract: instantiate a local subclass here, or use`,
        `    " cl_abap_testdouble against the interface it implements.`,
      ]
    : [
        ...(hasCtorParams
          ? [`    " TODO: constructor takes parameters — supply them here.`]
          : []),
        `    cut = NEW #( ).`,
      ];

  const impl = [
    `CLASS ${ltc} IMPLEMENTATION.`,
    `  METHOD setup.`,
    ...setupBody,
    `  ENDMETHOD.`,
    ...testMethods.flatMap((m) => [
      `  METHOD ${m}.`,
      `    " given … when … then`,
      `    cl_abap_unit_assert=>fail( msg = 'TODO: exercise ${cutName}${m === "instantiation" ? "" : `->${m}`}' ).`,
      `  ENDMETHOD.`,
    ]),
    `ENDCLASS.`,
  ].join("\n");

  return `${defn}\n\n${impl}\n`;
}

export function scaffoldAbapUnit(
  files: AbapSource[],
  abapVersion: AbapVersion = "v758",
): UnitTestResult {
  const outlines = outlineAbap(files);
  const out: UnitTestFile[] = [];
  const skipped: UnitTestResult["skipped"] = [];
  const validationInput: AbapSource[] = [];

  for (const o of outlines) {
    if (!o.parseable) {
      skipped.push({ object: o.file, reason: "not parseable — fix syntax first" });
      continue;
    }
    const cut = o.classes.find((c) => c.isGlobal && !c.isForTesting);
    if (cut === undefined) {
      const reason =
        o.classes.length > 0
          ? "only local or FOR TESTING classes — target the global class file"
          : o.interfaces.length > 0
            ? "interface — test its implementing class instead"
            : "no class definition found (programs: wrap logic in a class first)";
      skipped.push({ object: o.file, reason });
      continue;
    }
    const filename = o.file.replace(/\.clas\.abap$/, ".clas.testclasses.abap");
    if (filename === o.file) {
      skipped.push({ object: o.file, reason: "not a .clas.abap file — tests attach to the class object" });
      continue;
    }
    const content = renderTestClass(cut);
    out.push({ filename, content, forClass: cut.name.toUpperCase(), validated: "abaplint" });
    const original = files.find((f) => inferFilename(f.source, f.filename) === o.file);
    if (original !== undefined) validationInput.push({ filename: o.file, source: original.source });
    validationInput.push({ filename, source: content });
  }

  if (out.length === 0) {
    throw invalidInput(
      `No global class to scaffold tests for. Skipped: ${skipped.map((s) => `${s.object} (${s.reason})`).join("; ") || "no input"}`,
    );
  }

  // Round-trip generated code (with its class under test) through the parser;
  // only findings on generated files count against the scaffold.
  const generatedNames = new Set(out.map((f) => f.filename));
  const { findings } = runAbaplint(validationInput, { version: abapVersion, preset: "syntax-only" });
  const validationIssues = findings.filter((f) => generatedNames.has(f.file));

  return {
    files: out,
    skipped,
    nextSteps: [
      "Paste each testclasses file into the class's Test Classes tab in ADT (or add it next to the .clas.abap in abapGit).",
      "Replace every cl_abap_unit_assert=>fail( ) marker with real given/when/then logic — the skeletons fail deliberately until you do.",
      "Isolate dependencies with cl_abap_testdouble (interfaces) or CDS test doubles (RAP reads) before asserting behavior.",
      "Run the tests in ADT (Ctrl+Shift+F10); wire them into your CI transport gate once green.",
    ],
    validationIssues,
  };
}
